export const randomVerb = () => {
    const verbs = [
      "être",
      "pleurer",
      "avoir",
      "aller",
      "faire",
      "enregistrer",
      "pêcher",
      "dire",
      "tousser",
      "rougir",
      "revêtir",
      "remettre",
      "frapper",
      "répandre",
      "presser",
      "refléter",
      "gérer",
      "rejeter",
      "mélanger",
      "reconduire",
      "méprendre",
      "jurer",
      "soutenir",
      "secouer",
      "ressentir",
      "louer",
      "nommer",
      "informer",
      "geindre",
      "féliciter",
      "éviter",
      "endormir",
      "emprunter",
      "dépenser",
      "conseiller",
      "confondre",
      "cheminer",
      "causer",
      "blaguer",
      "augmenter",
      "arracher",
      "annoncer",
      "admirer",
      "adjoindre",
      "acquérir",
      "accueillir",
      "accrocher",
      "accourir",
      "accorder",
      "acclamer",
      "tomber",
      "souhaiter",
      "visiter",
      "remplacer",
      "reconnaître",
      "noter",
      "enseigner",
      "effacer",
      "décrire",
      "cuire",
      "coûter",
      "goûter",
      "ajouter",
      "allumer",
      "éteindre",
      "traduire",
      "épeler",
      "laver",
      "annuler",
      "permettre",
      "oser",
      "accompagner",
      "signer",
      "répéter",
      "remercier",
      "arranger",
      "inviter",
      "crier",
      "craindre",
      "approcher",
      "épouser",
      "supposer",
      "maintenir",
      "détester",
      "danser",
      "embrasser",
      "pardonner",
      "rire",
      "intéresser",
      "amuser",
      "terminer",
      "refuser",
      "accepter",
      "présenter",
      "chanter",
      "conduire",
      "choisir",
      "préparer",
      "offrir",
      "préférer",
      "coucher",
      "utiliser",
      "recevoir",
      "adorer",
      "agir",
      "expliquer",
      "vendre",
      "décider",
      "apporter",
      "bouger",
      "compter",
      "valoir",
      "fermer",
      "rencontrer",
      "sauver",
      "répondre",
      "raconter",
      "pouvoir",
      "continuer",
      "toucher",
      "emmener",
      "quitter",
      "monter",
      "lire",
      "rappeler",
      "acheter",
      "gagner",
      "retrouver",
      "écrire",
      "servir",
      "prier",
      "porter",
      "asseoir",
      "garder",
      "boire",
      "apprendre",
      "envoyer",
      "marcher",
      "occuper",
      "dormir",
      "excuser",
      "changer",
      "ouvrir",
      "tirer",
      "payer",
      "commencer",
      "devenir",
      "entrer",
      "manger",
      "travailler",
      "oublier",
      "tenir",
      "rendre",
      "vivre",
      "rentrer",
      "sentir",
      "perdre",
      "finir",
      "jouer",
      "revenir",
    ];
    const randomIndex = Math.floor(Math.random() * verbs.length);
    return verbs[randomIndex];
  };

  export const randomPronoun = () => {
    const pronoun = [
      "je",
      "tu",
      "il",
      "elle",
      "on",
      "vous",
      "nous",
      "ils",
      "elles",
    ];
    const randomIndex = Math.floor(Math.random() * pronoun.length);
    return pronoun[randomIndex];
  };

  export const randomTenses = () => {
    const tenses = [
      "à l'imparfait",
      "au passé composé",
      "au futur simple",
      "au présent",
      "au conditionnel présent",
    ];
    const randomIndex = Math.floor(Math.random() * tenses.length);
    return tenses[randomIndex];
  };